// <auto-generated />
using System;
using BlazorAppProject.Modelo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorAppProject.Migrations
{
    [DbContext(typeof(CatalogoDBContext))]
    [Migration("20240519003024_inicial5")]
    partial class inicial5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorAppProject.Modelo.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("RentaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RentaId");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("BlazorAppProject.Modelo.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EquipoId")
                        .HasColumnType("int");

                    b.Property<string>("EquipoRenta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("RentaId")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId");

                    b.HasIndex("RentaId");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("BlazorAppProject.Modelo.Renta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Equipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("Fecha")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Rentas");
                });

            modelBuilder.Entity("BlazorAppProject.Modelo.Equipo", b =>
                {
                    b.HasOne("BlazorAppProject.Modelo.Renta", null)
                        .WithMany("Equipos")
                        .HasForeignKey("RentaId");
                });

            modelBuilder.Entity("BlazorAppProject.Modelo.Persona", b =>
                {
                    b.HasOne("BlazorAppProject.Modelo.Equipo", "Equipo")
                        .WithMany("Personas")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorAppProject.Modelo.Renta", null)
                        .WithMany("Personas")
                        .HasForeignKey("RentaId");

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("BlazorAppProject.Modelo.Equipo", b =>
                {
                    b.Navigation("Personas");
                });

            modelBuilder.Entity("BlazorAppProject.Modelo.Renta", b =>
                {
                    b.Navigation("Equipos");

                    b.Navigation("Personas");
                });
#pragma warning restore 612, 618
        }
    }
}
